server:
  port: 8052
  host: 10.2.6.147

spring:
  application:
    name: ansv-registry-service


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://10.2.6.147:8052/eureka

logging:
  level:
    root: debug
  org:
    springframework: debug
  hibernate:
    SQL: true
