server:
  port: 8052
  host: 172.17.0.5

spring:
  application:
    name: ansv-registry-service


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://172.17.0.5:8052/eureka

logging:
  level:
    root: debug
  org:
    springframework: debug
  hibernate:
    SQL: true
